# import module
import os
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

# function to establish a new connection
def createNewConnection(SSID, password):

	wifiConfigContent = """<?xml version=\"1.0\"?>
	<WLANProfile xmlns="http://www.microsoft.com/networking/WLAN/profile/v1">
		<name>"""+SSID+"""</name>
		<SSIDConfig>
			<SSID>
				<name>"""+SSID+"""</name>
			</SSID>
		</SSIDConfig>
		<connectionType>ESS</connectionType>
		<connectionMode>auto</connectionMode>
		<MSM>
			<security>
				<authEncryption>
					<authentication>WPA2PSK</authentication>
					<encryption>AES</encryption>
					<useOneX>false</useOneX>
				</authEncryption>
				<sharedKey>
					<keyType>passPhrase</keyType>
					<protected>false</protected>
					<keyMaterial>"""+password+"""</keyMaterial>
				</sharedKey>
			</security>
		</MSM>
	</WLANProfile>"""

	# with open("config.xml", "r") as wifiConfig:
	# 	wifiConfigContent = wifiConfig.readlines()
	# 	for i, line in enumerate(wifiConfigContent):
	# 		if line.find("<name>{name}</name>") != -1:
	# 			wifiConfigContent[i] = line.replace("<name>{name}</name>", f"<name>{SSID}</name>")
	# 		elif line.find("<name>{SSID}</name>") != -1:
	# 			wifiConfigContent[i] = line.replace("<name>{SSID}</name>", f"<name>{SSID}</name>")
	# 		elif line.find("<keyMaterial>{password}</keyMaterial>") != -1:
	# 			wifiConfigContent[i] = line.replace("<keyMaterial>{password}</keyMaterial>", f"<keyMaterial>{password}</keyMaterial>")

	with open(f"config.xml", 'w') as wifiConfig:
		wifiConfig.write(wifiConfigContent)

	command = f'netsh wlan add profile filename="config.xml" interface=Wi-Fi'
	os.system(command)

# function to connect to a network
def connect(SSID):
	command = f'netsh wlan connect name="{SSID}" ssid="{SSID}" interface=Wi-Fi'
	os.system(command)

# function to display avavilabe Wifi networks
def displayAvailableNetworks():
	command = "netsh wlan show networks interface=Wi-Fi"
	os.system(command)

if __name__ == "__main__":
	# display available netwroks
	displayAvailableNetworks()
	# add teraiot@ to all deivce ids and create a list of device ids and passwords

	"""
		This Script will automatically connect to the wifi network which generated by
		each ESP8266 device with its correcponding device id
	"""

	SSIDS = [f"teraiot@{i}" for i in range(600, 601)]
	PASSWORDS = ["teraiot@143" for _ in SSIDS]
	WIFI_SSID = "avbhaskar"
	WIFI_PASSWORD = "sitaramarao"
	CONFIG_IP = "http://80.80.80.1"

	for SSID, PASSWORD in zip(SSIDS, PASSWORDS):
		driver = webdriver.Firefox()

		print(30*"--")
		createNewConnection(SSID, PASSWORD)
		print(30*"--")

		# connect to the wifi network
		connect(SSID)
		time.sleep(5)
		driver.get(CONFIG_IP)

		wifiButton = driver.find_element(by = By.XPATH, value = "/html/body/div/form[1]/button")
		wifiButton.click()

		ssid_field = driver.find_element(by = By.NAME, value = "s")
		ssid_field.send_keys(WIFI_SSID)

		password_field = driver.find_element(by = By.NAME, value = "p")
		password_field.send_keys(WIFI_PASSWORD)

		save_button = driver.find_element(by = By.XPATH, value = "/html/body/div/form[1]/button")
		save_button.click()

		driver.close()
		time.sleep(5)